title: Snehal Nair
email: snehal.1409@gmail.com
description: Resume and project portfolio
url: ""
baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/
