title: Snehal Nair
email: snehal.1409@gmail.com
description: Resume and project portfolio
url: ""
baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
future: true
header_pages:
  - index.md
  - portfolio.md
  - publications.md
  - cv.md
  - blog.md
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/
